[package]
name = "wiiland-dump"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
description = "Wii Remote EEPROM dumper"

[lib]
name = "wiiland_dump"
path = "src/lib.rs"

[[bin]]
name = "wiiland-dump"
path = "src/main.rs"

[dependencies]
libc.workspace = true
