.\"
.\" Written 2012 by David Herrmann
.\" Dedicated to the Public Domain
.\"
.TH "LIBXWIIMOTE" 7 "February 2012" "David Herrmann" "Wii Remote Driver"
.SH NAME
libxwiimote \- WiiLand compatibility user-space library

.SH SYNOPSIS
.B #include <xwiimote.h>

.SH DESCRIPTION
The libxwiimote compatibility library manages connected Wii Remotes from
user-space. If you write an application that wants to support Wii Remotes as
input devices but you cannot rely on X or the kernel to provide a suitable input
device for you (for example, because you need finer grained access), then you
can use this library to access Wii Remotes.

This library provides a simple, but still comprehensive, API to access
connected Wii Remotes. The API documentation is still in process. Please read
the tools in wiiland/tools/ or the header in wiiland/lib/xwiimote.h for
information on the API.

.SH BUGS
The library does not support all Wii Remote peripherals, yet. Please consider
contributing to the project if you need further functionality.

.SH AUTHOR
David Herrmann <dh.herrmann@googlemail.com>
.br
The WiiLand Project: https://github.com/PhilosophiMoonbeam/wiiland

.SH "SEE ALSO"
.BR wiiland (7),
.BR wiilandd (1),
.BR xwiishow (1)
